kitchen/urls.py
from django.urls import path

from kitchen.views import (
    IndexView,
    DishTypeListView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    CookListView,
    CookDetailView,
    CookCreateView,
    CookUpdateView,
    CookDeleteView,
    DishDetailView,
    DishListView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
)


urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("dish_types/", DishTypeListView.as_view(), name="dish_type-list"),
    path("dish_types/create/", DishTypeCreateView.as_view(), name="dish_type-create"),
    path(
        "dish_types/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dish_type-update",
    ),
    path(
        "dish_types/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dish_type-delete",
    ),
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path("cooks/<int:pk>/update/", CookUpdateView.as_view(), name="cook-update"),
    path("cooks/<int:pk>/delete/", CookDeleteView.as_view(), name="cook-delete"),
    path("dishes/", DishListView.as_view(), name="dish-list"),
    path("dishes/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path("dishes/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("dishes/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
]

app_name = "kitchen"

kitchen_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

templates/includes/footer.html
<footer class="footer pt-5 mt-5">
  <hr class="horizontal dark mb-5">
  <div class="col-12">
    <div class="text-center">
    </div>
  </div>       
</footer>

templates/includes/navigation.html
  <div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <div class="col-12">
        <nav class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
          <div class="container-fluid">
            <a class="navbar-brand font-weight-bolder ms-sm-3" 
               href="/" rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom">
              Restaurant Home Page
            </a>         
            <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0" id="navigation">
              <ul class="navbar-nav navbar-nav-hover ms-lg-12 ps-lg-5 w-100">
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center" id="dropdownMenuPages" data-bs-toggle="dropdown" aria-expanded="false">
                    Menu
                    <img src="/static/assets/img/down-arrow-dark.svg" alt="down-arrow" class="arrow ms-1">
                  </a>
                  <div class="dropdown-menu dropdown-menu-animation dropdown-md p-3 border-radius-lg mt-0 mt-lg-3" aria-labelledby="dropdownMenuPages">
                    <div class="d-none d-lg-block">
                      <a href="/dish_types/" class="dropdown-item border-radius-md">
                        Our Dish Type
                      </a>
                      <a href="/dishes" class="dropdown-item border-radius-md">
                        Our Dishes
                      </a>
                      <a href="/cooks" class="dropdown-item border-radius-md">
                        Our Cooks
                      </a>
                    </div>
                  </div> 
                </li>
              </ul>
              <p class="nav-item my-auto ms-3 ms-lg-0">
                <a href="{% url 'logout' %}"
                   class="btn btn-sm  bg-gradient-primary  btn-round mb-0 me-1 mt-2 mt-md-0">Logout</a>
              </p>
            </div>
          </div>
        </nav>
        <!-- End Navbar -->
      </div>
    </div>
  </div>
  

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link>" href="?{% query_transform request page=page_obj.previous_page_number %}">Prev</a>
        </li>
      {% endif %}
      <li class="page-item active"><span class="page-link" style="font-size: 12px;">{{ page_obj.number }} of {{ paginator.num_pages }}</span></li>
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link>" href="?{% query_transform request page=page_obj.next_page_number %}">Next</a>
        </li>
      {% endif %}
    </ul>
  {% endif %}

templates/includes/scripts.html
  <script src="/static/assets/js/core/popper.min.js" type="text/javascript"></script>
  <script src="/static/assets/js/core/bootstrap.min.js" type="text/javascript"></script>
  <script src="/static/assets/js/plugins/perfect-scrollbar.min.js"></script>
  <script src="/static/assets/js/plugins/prism.min.js"></script>
  <script src="/static/assets/js/plugins/parallax.min.js"></script>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
    <li class="list-group-item">User: <a href="{{ user.get_absolute_url }}">{{ user.get_username }}</a></li>
    <li class="list-group-item">
      <form method="post" action="{% url 'logout' %}?next=/">
    {% csrf_token %}
    <button type="submit">Log Out</button>
      </form>
    </li>
  {% else %}
    <li class="list-group-item"><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
  {% endif %}
  <br>
  <li class="list-group-item">
    <a href="{% url 'kitchen:index' %}">Home</a>
  </li>
  <li class="list-group-item">
    <a href="{% url 'kitchen:cook-list' %}">All cooks</a>
  </li>
  <li class="list-group-item">
    <a href="{% url 'kitchen:dish-list' %}">All dishes</a>
  </li>
  <li class="list-group-item">
    <a href="{% url 'kitchen:dish_type-list' %}">All dishes types</a>
  </li>
</ul>